### ISSUE TITLE
Print versions at the end of report

### ISSUE THREAD

**Issue by ktrns** [ktrns/scrnaseq#18]
How about printing the repository version and R packages versions at the end of the HTML report? This is done for nf-core pipelines for example, and is useful for the user when writing the paper.

**Comment by tglomb** [comment]
This sounds like a good idea. Furthermore I would include a link to the Github repo or directly to the particular version of the repo.

**Comment by ktrns** [comment]
How about something like this? 
 
<img width="721" alt="Screenshot 2020-05-28 at 21 53 30" src="https://user-images.githubusercontent.com/9417927/83187024-c6417400-a12d-11ea-933d-32206071a105.png">

**Comment by Oliver-D-B** [comment]
This looks really professional in my view. Possibly, we might consider to even include the entirety of settings and parameters to the end in a similar way. But let's discuss this point along with additional ideas to optimize script and report (in order to have a good balance of work and effective improvement).
