### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by colindaven** [ktrns/scrnaseq#3]
Hi Oliver/Marius.
@mariusrueve

you can watch this repo (button top right) to be notified of all conversations, issues, pull requests (PRs) etc.

You can address people with @colindaven like in gitlab.

I'm not sure who can assign issues to users, perhaps only owners/maintainers like @ktrns ? 

Best wishes,
Colin

**Comment by ktrns** [comment]
Hi @colindaven,  

At the moment, my Dresden colleagues are "Collaborators" and have commit access to the main repository of the project. All collaborators can assign issues to collaborators. 

You guys are "Contributors" and made forks, and we can merge your changes through pull requests. 

Question is, would you guys like to be collaborators rather than contributors? Have a look here: 
https://www.pluralsight.com/blog/software-development/the-definitive-guide-to-forks-and-branches-in-git

Best wishes
Katrin

**Comment by colindaven** [comment]
Hi @ktrns 

I think contributors is fine, we can make PRs and have you and your colleagues check them over.

Thanks,
Colin
