### ISSUE TITLE
Prefix for metadata

### ISSUE THREAD

**Issue by ktrns** [ktrns/scrnaseq#71]
Let's fix the way we handle metadata column names in case we deal with multiple samples (with equal column names). 

* Writing in HTO script
* Reading in the main script

**Comment by andpet0101** [comment]
* Writing in the HTO script: We include only `HTO_classification` and `HTO_hash_id` at the moment in the cell metadata. When we later read multiple HTO datasets, these collumns will be combined - no prefix neccessary.

* Reading in the main script: Columns with the same name will be combined - if not, then the user has to name them accordingly - no prefix neccessary

* Writing in the main script: As part of the output, I will write the counts together with the metadata as files so that they can be used for another round of analysis. Here I will add the project id as prefix.
