### ISSUE TITLE
Improve output

### ISSUE THREAD

**Issue by ktrns** [ktrns/scrnaseq#74]
Let's collect ideas of what else would be useful to add to the output: 

- plots as objects, in addition to pdf and png

**Comment by andpet0101** [comment]
* raw counts plus metadata such that one can do a second analysis where one keeps only cells in cluster 1 (this could be done via the filter options)
* counts/data/z-scores for a representative set of cells (e.g. 500) as table together with metadata so that the user can plot their own heatmaps as csv/excel
* cerebroApp/cellxgene/ucsc cell browser
* full metadata table as as csv/excel
* table with seurat name plus ensembl annotation
