### ISSUE TITLE
Output files for differentially expressed genes

### ISSUE THREAD

**Issue by ktrns** [ktrns/scrnaseq#80]
Contrasts: Can we have ONE file with one tab per contrast? (as we have one tab per cluster for marker genes)

Functions: I'd prefer if we only write files if there is something to write, i.e. there are enriched functions and so on... In my current report, there are no enrichments, but a tab called "All" with only the headers.

**Comment by andpet0101** [comment]
Regarding the contrasts: What do you do with subsets? No I think one file per contrast is good especially since contrasts may be separate analyses.

Functions: Maybe but on the other hand I think that an empty table is more informative - it tells you that there were no DEGs. A missing file could be interpreted as a bug.
